### ISSUE TITLE
Share setup guidance for dev environment with project members

### ISSUE THREAD

**Issue by noenemy** [noenemy/reinvent2018-got-talent#2]

**Comment by noenemy** [comment]
@liks79 
I updated Readme.md file. Please see the section 3. Development Environment Setup (macOS)

**Comment by liks79** [comment]
@noenemy Thanks!
However, in my case, `ng serve` doesn't work with following errors.
```console
ng serve
Could not find module "@angular-devkit/build-angular" from "/Users/sungshik/playground/reinvent2018-got-talent/GotTalent-Web".
Error: Could not find module "@angular-devkit/build-angular" from "/Users/sungshik/playground/reinvent2018-got-talent/GotTalent-Web".
    at Object.resolve (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at DoOperator.call (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:32:23)
    at Observable.subscribe (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:25:22)
    at /Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/Users/sungshik/.nvm/versions/node/v8.9.1/lib/node_modules/
``` 

So, I recognized. I need `npm install` is required.
However `npm install` also failed due to python2 dependencies below.
There is no python2 in my macbook environment because I used `pyenv` with python 3.6.3.

```console
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/sungshik/.pyenv/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.14
gyp ERR! stack   2.7.14/envs/venv-2.7.14
gyp ERR! stack   venv-2.7.14
gyp ERR! stack
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/sungshik/.nvm/versions/node/v8.9.1/bin/node" "/Users/sungshik/playground/reinvent2018-got-talent/GotTalent-Web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/sungshik/playground/reinvent2018-got-talent/GotTalent-Web/node_modules/node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
``` 
So, I change my `pyenv` environment from python 3.6.3 to python 2.7.14 then I can reach out.

Fixed Setup guide is committed.  

https://github.com/noenemy/reinvent2018-got-talent/commit/7354b451eb6e4c0786edd72a45c101e16028f0e5

**Comment by noenemy** [comment]
@liks79 I think there's a typo in my first setup guide. The following steps are enough to run angularJs project. I changed 'ng update' to 'npm update'. 👍 
- npm update
- ng serve

**Comment by noenemy** [comment]
Closing.
